### PR TITLE
Use Redux in React components

### PR DESCRIPTION
**Pull request by anderCM**
- Connect your store to the main component of your React app.
- Define a state slice which will contain your books.
- Display your books, received from the slice, in a reusable component
- Dispatch actions using useDispatch
- Add a <Button> component, which includes:
  - An event handler that adds a book to the books array (with attributes id, title and author)
- Add a <Button> component, which includes:
  - An event handler that removes a book to the books array (by id)
- Add a <Button> component, which includes:
  - An event handler that filters a categories of the categories array (by country)

### CODE REVIEW

**Comment by anderCM** [comment]
The last requirement is not clear because in previous requeriments we didn't have to add a country to the book, even in the picture there is not country. I think it's an error, so please let me know if it is.

**Review by FrederickMih — CHANGES_REQUESTED** [review]
## Hi :raising_hand:  @anderCM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!





## Highlights :green_circle: 

- PR is professional :+1: 
- Adding and Removing book is possible :+1: 
- Linter checks passed :heavy_check_mark: 


## Required Changes ♻️

- [x] Hi @anderCM you still need to modify the component responsible for rendering categories. Based on the requirements of this project, this component should contain a button for checking the status :+1: This button will **use** a function `checkCategoriesStatus`(name can be different) made in the **Categories** component. `checkCategoriesStatus` dispatches the `underConstruction` action creator(name can be different). Let's kindly adhere to these requirements and move a step forward toward approval :+1: 
- **NB** General comment is left here since you didn't push changes made in the Categories component.

_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Munsa1 — APPROVED** [review]
Sorry @anderCM  I let the review go by mistake someone else will review it for you

**Review by Ghiftee — APPROVED** [review]
## STATUS: APPROVED ♻️♻️
Hi @anderCM, 

To highlight 👍🏽 
✔️ App runs smoothly
✔️ No linter errors

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Pull request merged**
